2024-04-21 14:00:37 - ERROR - Exception on /maintain_assets [GET]
Traceback (most recent call last):
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\app\admin\routes.py", line 15, in maintain_assets
    return render_template("maintain_assets.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\app\admin\templates\maintain_assets.html", line 1, in top-level template code
    {% extends "layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\app\main\templates\layout.html", line 48, in top-level template code
    {% block content %}
  File "C:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\app\admin\templates\maintain_assets.html", line 7, in block 'content'
    <td><a href='{{url_for("admin.add_assets")}}' class='btn btn-primary'>Add Asset</a></td>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\werkzeug\routing\map.py", line 926, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'admin.add_assets'. Did you mean 'admin.add_asset' instead?
2024-04-21 14:54:25 - ERROR - Exception on /edit_asset [GET]
Traceback (most recent call last):
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: edit_asset() missing 1 required positional argument: 'id'
2024-04-21 14:54:29 - ERROR - Exception on /edit_asset [GET]
Traceback (most recent call last):
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: edit_asset() missing 1 required positional argument: 'id'
2024-04-21 14:56:06 - ERROR - Exception on /edit_asset [GET]
Traceback (most recent call last):
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ellie\OneDrive\Documents\Programming\Python\Level 6\Major Project\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: edit_asset() missing 1 required positional argument: 'asset_id'
